version: "3.7"
services:
  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "admin" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - APP_DB_NAME=tasktrack
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
